
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '8.0'

target 'FFCategoryKit_Example' do
  pod 'FFCategoryKit', :path => '../'

  target 'FFCategoryKit_Tests' do
    inherit! :search_paths

    
  end
end
